ALTER PROC [dbo].[FI_SP_ConsBeneficiario]
	@IdBeneficiario BIGINT
AS
BEGIN
	IF(ISNULL(@IdBeneficiario,0) = 0)
		SELECT CPF, NOME, IDCLIENTE , ID FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE
		SELECT CPF, NOME, IDCLIENTE , ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @IdBeneficiario
END